---

- name: copy the script to build the tool list
  become: yes
  become_user: galaxypa
  copy: src=list_repos.py dest=~/src/list_repos.py

- name: copy the tool installation script
  become: yes
  become_user: galaxypa
  copy: src=install_tool_shed_tools.py dest=~/src/install_tool_shed_tools.py


- name: create tool list using a galaxy and a toolshed as reference
  become: yes
  become_user: galaxypa
  shell: source .venv/bin/activate && python ~/src/list_repos.py --url_galaxy_ref {{ url_galaxy_ref }} --url_galaxy_target {{ url_galaxy_target }} --adminkey_galaxy_target {{ target_apikey }}  --url_toolshed {{ url_toolshed }} --output_yaml ~/src/tools.yaml chdir=~/galaxy

- name: Ensure galaxy is running and enabled
  service: name=galaxy state=running enabled=yes sleep=5


- name: install the tools on the galaxy target
  become: yes
  become_user: galaxypa
  shell: source .venv/bin/activate && python ~/src/install_tool_shed_tools.py --galaxy {{ url_galaxy_target }} --apikey {{ target_apikey }} -t ~/src/tools.yaml --toolshed {{ url_toolshed }} chdir=~/galaxy
  notify:
    - restart galaxy

- name: Ensure galaxy is running and enabled
  service: name=galaxy state=running enabled=yes

