---
- name: Clone galaxy conf
  become: yes
  become_user: galaxypa
  git: repo={{ galaxy_conf }} dest=~/galaxy_conf

- name: copy conf files
  become: yes
  become_user: galaxypa
  #command: rsync -r ~/galaxy_conf/ ~/galaxy
  synchronize:
    src: /home/galaxypa/galaxy_conf/
    dest: /home/galaxypa/galaxy
  delegate_to: "{{ inventory_hostname }}"

- name: fetch eggs
  become: yes
  become_user: galaxypa
  shell: source .venv/bin/activate && python scripts/fetch_eggs.py chdir=~/galaxy
  ignore_errors: yes

- name: init_db galaxy
  become: yes
  become_user: galaxypa
  shell: source .venv/bin/activate & sh manage_db.sh version_control && sh manage_db.sh upgrade chdir=~/galaxy
  notify:
    - restart galaxy

- name: Ensure galaxy is running and enabled
  service: name=galaxy state=running enabled=yes