---
- name: Install Galaxy Pasteur
  hosts: ifb
  remote_user: root

  roles:
    - {role: postgresql, tags: ['postgresql']}
    - {role: system_dependancies, tags: ['system']}
    - {role: galaxy, tags: ['galaxy']}
    - {role: galaxy_conf, tags: ['galaxy']}
    - {role: python, tags: ['python']}
    - {role: python_dependancies, tags: ['python']}
    - {role: apache, tags: ['apache']}