---
- name: Install Galaxy Pasteur
  hosts: ifb
  remote_user: root


  roles:
    - {role: create_user, tags: ['user']}
    - {role: git_install, tags: ['git']}
    - {role: python, tags: ['python']}
    - {role: galaxy, tags: ['galaxy']}
