---
- name: Install postgresql
  yum: name=postgresql-server.x86_64 state=installed

- name: initdb postgresql
  command: service postgresql initdb creates=/var/lib/pgsql/data/pg_hba.conf

- name: Add galaxy authentication in pg_hba.conf
  blockinfile:
    dest: /var/lib/pgsql/data/pg_hba.conf
    insertafter: "# TYPE  DATABASE    USER        CIDR-ADDRESS          METHOD"
    content: |
      local   {{ user_postgres }}         {{ user_postgres }}                                md5
      host    {{ user_postgres }}         {{ user_postgres }}          124.0.0.1/32          md5
      host    {{ user_postgres }}         {{ user_postgres }}          ::1/128               md5
  notify:
    - restart postgresql

- name: Ensure postgresql is running and enabled
  service: name=postgresql state=running enabled=yes