---
- name: Install postgresql
  yum: name=postgresql-server.x86_64 state=installed

- name: initdb postgresql
  command: service postgresql initdb creates=/var/lib/pgsql/data/pg_hba.conf

- name: Add galaxy authentication in pg_hba.conf
  blockinfile:
    dest: /var/lib/pgsql/data/pg_hba.conf
    insertafter: "# TYPE  DATABASE    USER        CIDR-ADDRESS          METHOD"
    content: |
      local   galaxy-pasteur         galaxy-pasteur                                md5
      host    galaxy-pasteur         galaxy-pasteur          124.0.0.1/32          md5
      host    galaxy-pasteur         galaxy-pasteur          ::1/128               md5

- name: Ensure postgresql is running
  service: name=postgresql state=started enabled=yes