---
- name: Creation of "galaxypa" user
  user: name=galaxypa comment="Application user" shell=/bin/bash state=present

- name: Clone galaxy pasteur
  become: yes
  become_user: galaxypa
  git: repo=https://github.com/C3BI-pasteur-fr/galaxy.git dest=~/galaxy
       version=pasteur

- name: psycopg2 install
  yum: name=python-psycopg2.x86_64 state=installed

- name: Create db user
  become: yes
  become_user: postgres
  postgresql_user: name={{ user_postgres }}

- name: Create db
  become: yes
  become_user: postgres
  postgresql_db: name={{ user_postgres }} owner={{ user_postgres }}

- name: init scripts copy
  template: src=galaxy dest=/etc/init.d/ mode=0744
